import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navegacion from "@/components/ui/Navegacion";
import Footer from "@/components/ui/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Construcciones Civiles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navegacion/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
